name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5.2.0
        with:
          distribution: temurin
          java-version: 17

      - name: Install Leiningen
        uses: ./.github/actions/setup-lein

      - name: Install project dependencies
        run: lein deps

      - name: Check formatting
        run: lein cljfmt check

      - name: Run tests
        run: lein test
